---
- hosts: all
  become: true
  tasks:
    - name: "Update etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: '{{ item }}'
      with_items:
        - '10.10.1.3  bastion'
        - '10.10.1.11 node-1 zabbix-web zabbix-server zabbix.example.com'
        - '10.10.1.12 node-2 zabbix-database'
        - '10.10.1.13 node-3 zabbix-proxy'

    - name: Install basic packages
      package:
        name:
          - ca-certificates
          - curl
          - python39
          - python39-pip
          - python39-PyMySQL
        state: present
        update_cache: True

    - name: "Installing Python module"
      pip:
        name: netaddr

    - name: Set authorized key taken from file
      authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', 'id_rsa.pub') }}"

    - name: Set timezone to America/Detroit
      community.general.timezone:
        name: America/Detroit
